Improve context path detection

diff --git a/.github/workflows/builds.yml b/.github/workflows/builds.yml
--- a/.github/workflows/builds.yml
+++ b/.github/workflows/builds.yml
@@ -45,12 +45,23 @@ jobs:
           NAME=$(head -n 1 ${{ matrix.dockerfile }} | awk '{print $2}')
           echo "name=${NAME}" >> $GITHUB_OUTPUT
 
-      - name: Fail if no Image Name detected
+      - name: Determine Context Path
+        id: detect-context-path
+        shell: bash
+        run: |
+          CONTEXT_PATH=$(dirname ${{ matrix.dockerfile }})
+          echo "path=${CONTEXT_PATH}" >> $GITHUB_OUTPUT
+
+      - name: Fail if parameters not detected
         shell: bash
         run: |
           if [ -z "${{ steps.detect-image-name.outputs.name }}" ]; then
             echo "::error::Failed to detect image name from Dockerfile ${{ matrix.dockerfile }}"
             exit 1
+          fi
+          if [ -z "${{ steps.detect-context-path.outputs.name }}" ]; then
+            echo "::error::Failed to detect context Path"
+            exit 2
           fi
 
       - name: Prepare Docker Image Names and Tags
@@ -83,7 +94,7 @@ jobs:
           platforms: linux/amd64,linux/arm64
           # Dependabot triggered PRs don't have credentials to push images
           push: ${{ github.actor != 'dependabot[bot]' }}
-          context: .
+          context: ${{ steps.detect-context-path.outputs.path }}
           file: ${{ matrix.dockerfile }}
           tags: ${{ steps.meta.outputs.tags }}
           build-args: |
